<?php

namespace Langsys\SDK\Tests\Format;

use Langsys\SDK\Format\Interpolator;
use Langsys\SDK\Tests\Support\SpyLogger;
use PHPUnit\Framework\TestCase;

/**
 * Tests for placeholder interpolation.
 *
 * Expected values in the ICU / locale-formatting tests are NOT hand-written -
 * they were generated by running the Langsys JS SDK's implementation, so a
 * failure here means the two SDKs would render a shared catalog differently.
 *
 * ICU-dependent tests skip when ext-intl is unavailable, matching the pattern
 * this repo already uses for Redis.
 */
class InterpolatorTest extends TestCase
{
    /**
     * @var Interpolator
     */
    protected $interpolator;

    protected function setUp(): void
    {
        $this->interpolator = new Interpolator();
    }

    /**
     * Skip when ext-intl is unavailable - unless LANGSYS_REQUIRE_INTL is set,
     * in which case fail instead.
     *
     * CI sets that variable so the ICU tests cannot silently skip on a runner
     * that was supposed to have intl. A green suite that skipped every plural
     * assertion is exactly the false confidence this guards against.
     */
    protected function requireIntl()
    {
        if (extension_loaded('intl')) {
            return;
        }

        if (getenv('LANGSYS_REQUIRE_INTL')) {
            $this->fail(
                'ext-intl is not loaded, but LANGSYS_REQUIRE_INTL is set. '
                . 'ICU plural/select behaviour would go unverified.'
            );
        }

        $this->markTestSkipped('ext-intl is not available');
    }

    /**
     * Skip when ext-intl IS present - these cover the degradation path, which
     * only exists when the extension is absent. The CI "Degradation without
     * ext-intl" job is where they actually execute.
     */
    protected function requireMissingIntl()
    {
        if (extension_loaded('intl')) {
            $this->markTestSkipped('This test covers the no-intl degradation path');
        }
    }

    // ---------------------------------------------------------------
    // Simple substitution - runs everywhere, no ext-intl needed
    // ---------------------------------------------------------------

    public function testSubstitutesSinglePlaceholder()
    {
        $this->assertEquals(
            'Hello, Sarah!',
            $this->interpolator->interpolate('Hello, {name}!', ['name' => 'Sarah'])
        );
    }

    public function testSubstitutesMultiplePlaceholders()
    {
        $this->assertEquals(
            'Sarah has 2 items',
            $this->interpolator->interpolate('{name} has {count} items', ['name' => 'Sarah', 'count' => '2'])
        );
    }

    public function testSubstitutesRepeatedPlaceholder()
    {
        $this->assertEquals(
            'Sarah, Sarah!',
            $this->interpolator->interpolate('{name}, {name}!', ['name' => 'Sarah'])
        );
    }

    public function testUnknownKeyLeftVerbatim()
    {
        $this->assertEquals(
            'Hello, Sarah! Bye {other}',
            $this->interpolator->interpolate('Hello, {name}! Bye {other}', ['name' => 'Sarah'])
        );
    }

    public function testNullValueLeftVerbatim()
    {
        $this->assertEquals(
            'Hello, {name}!',
            $this->interpolator->interpolate('Hello, {name}!', ['name' => null])
        );
    }

    public function testWhitespaceInsidePlaceholderTolerated()
    {
        $this->assertEquals(
            'Hi Sarah!',
            $this->interpolator->interpolate('Hi { name }!', ['name' => 'Sarah'])
        );
    }

    public function testEmptyParamsReturnsTextUnchanged()
    {
        $this->assertEquals(
            'Hello, {name}!',
            $this->interpolator->interpolate('Hello, {name}!', [])
        );
    }

    public function testTextWithoutPlaceholdersUnchanged()
    {
        $this->assertEquals(
            'Nothing to do here',
            $this->interpolator->interpolate('Nothing to do here', ['name' => 'Sarah'])
        );
    }

    public function testArrayValueLeftVerbatim()
    {
        $this->assertEquals(
            'Value: {v}',
            $this->interpolator->interpolate('Value: {v}', ['v' => ['a', 'b']])
        );
    }

    public function testObjectWithToStringIsUsed()
    {
        $obj = new class {
            public function __toString()
            {
                return 'stringified';
            }
        };

        $this->assertEquals(
            'Value: stringified',
            $this->interpolator->interpolate('Value: {v}', ['v' => $obj])
        );
    }

    public function testBooleansRenderAsJsStyleTrueFalse()
    {
        // Matches JS String(bool), NOT PHP's native "1" / "".
        $this->assertEquals(
            'a=true b=false',
            $this->interpolator->interpolate('a={a} b={b}', ['a' => true, 'b' => false])
        );
    }

    // ---------------------------------------------------------------
    // Dollar-sign / backreference safety
    //
    // Regression guard: preg_replace would treat $1 / \1 in the REPLACEMENT
    // as backreferences. The JS SDK shipped the equivalent fix in 0.4.1.
    // ---------------------------------------------------------------

    public function testDollarSignInValueNotMangled()
    {
        $this->assertEquals(
            'Price: $5',
            $this->interpolator->interpolate('Price: {price}', ['price' => '$5'])
        );
    }

    public function testBackreferenceLikeValuesNotMangled()
    {
        $this->assertEquals(
            'a=$1 b=\1 c=$& d=$0',
            $this->interpolator->interpolate(
                'a={a} b={b} c={c} d={d}',
                ['a' => '$1', 'b' => '\1', 'c' => '$&', 'd' => '$0']
            )
        );
    }

    public function testDollarSignInSurroundingTextPreserved()
    {
        $this->assertEquals(
            '$5 & $& stays, Sarah',
            $this->interpolator->interpolate('$5 & $& stays, {name}', ['name' => 'Sarah'])
        );
    }

    // ---------------------------------------------------------------
    // Detection helpers
    // ---------------------------------------------------------------

    public function testDetectsIcuSyntax()
    {
        $this->assertTrue($this->interpolator->hasIcuSyntax('{n, plural, one {# item} other {# items}}'));
        $this->assertTrue($this->interpolator->hasIcuSyntax('{g, select, female {She} other {They}}'));
        // Style-less forms must match too.
        $this->assertTrue($this->interpolator->hasIcuSyntax('{v, number}'));
        $this->assertTrue($this->interpolator->hasIcuSyntax('{d, date}'));

        $this->assertFalse($this->interpolator->hasIcuSyntax('Hello, {name}!'));
        $this->assertFalse($this->interpolator->hasIcuSyntax('No placeholders'));
    }

    public function testDetectsPlainPlaceholders()
    {
        $this->assertTrue($this->interpolator->hasPlaceholders('Hello, {name}!'));
        $this->assertFalse($this->interpolator->hasPlaceholders('Hello!'));
    }

    // ---------------------------------------------------------------
    // Missing-intl behaviour: warn loudly, degrade to simple substitution.
    // This is the path that is actually exercised on a host without intl.
    // ---------------------------------------------------------------

    public function testIcuWithoutIntlWarnsAndFallsBackToSimpleSubstitution()
    {
        if (extension_loaded('intl')) {
            $this->markTestSkipped('This test covers the no-intl degradation path');
        }

        $logger = new SpyLogger();
        $interpolator = new Interpolator($logger);

        $result = $interpolator->interpolate(
            'Hello {name}, you have {n, plural, one {# item} other {# items}}',
            ['name' => 'Sarah', 'n' => 2],
            'en-US'
        );

        // Simple placeholders still resolve; the ICU slot is left visible.
        $this->assertStringContainsString('Hello Sarah,', $result);

        $warnings = $logger->messagesAt('warning');
        $this->assertNotEmpty($warnings, 'A missing-intl warning must be logged');
        $this->assertStringContainsString('ext-intl', $warnings[0]);
    }

    public function testMissingIntlWarningEmittedOnlyOncePerInstance()
    {
        if (extension_loaded('intl')) {
            $this->markTestSkipped('This test covers the no-intl degradation path');
        }

        $logger = new SpyLogger();
        $interpolator = new Interpolator($logger);

        $icu = '{n, plural, one {# item} other {# items}}';
        $interpolator->interpolate($icu, ['n' => 1], 'en-US');
        $interpolator->interpolate($icu, ['n' => 2], 'en-US');
        $interpolator->interpolate($icu, ['n' => 5], 'en-US');

        $this->assertCount(1, $logger->messagesAt('warning'));
    }

    /**
     * Without ext-intl an ICU phrase must still read as a SENTENCE.
     *
     * Simple substitution cannot match a construct containing commas and nested
     * braces, so before this fallback existed the raw MessageFormat source was
     * emitted to the page - worse output than an untranslated phrase.
     */
    public function testIcuPluralRendersReadableTextWithoutIntl()
    {
        $this->requireMissingIntl();

        $pattern = '{n, plural, one {# item} other {# items}}';

        $this->assertEquals('1 item', $this->interpolator->interpolate($pattern, ['n' => 1], 'en-US'));
        $this->assertEquals('5 items', $this->interpolator->interpolate($pattern, ['n' => 5], 'en-US'));

        foreach ([1, 5] as $n) {
            $this->assertStringNotContainsString(
                'plural',
                $this->interpolator->interpolate($pattern, ['n' => $n], 'en-US'),
                'Raw MessageFormat source must never reach the page'
            );
        }
    }

    /**
     * Exact `=N` branches are standards-correct and safe without CLDR data.
     */
    public function testIcuExactBranchIsUsedWithoutIntl()
    {
        $this->requireMissingIntl();

        $pattern = '{n, plural, =0 {no items} one {# item} other {# items}}';

        $this->assertEquals('no items', $this->interpolator->interpolate($pattern, ['n' => 0], 'en-US'));
        $this->assertEquals('1 item', $this->interpolator->interpolate($pattern, ['n' => 1], 'en-US'));
    }

    /**
     * A language whose correct category we cannot compute degrades to a single
     * readable form rather than leaking markup.
     */
    public function testRussianPluralDegradesToReadableTextWithoutIntl()
    {
        $this->requireMissingIntl();

        $result = $this->interpolator->interpolate(
            '{n, plural, one {# товар} few {# товара} other {# товаров}}',
            ['n' => 3],
            'ru-RU'
        );

        $this->assertStringNotContainsString('plural', $result);
        $this->assertStringNotContainsString('{', $result);
        $this->assertStringContainsString('3', $result);
    }

    public function testIcuSelectWorksWithoutIntl()
    {
        $this->requireMissingIntl();

        $pattern = '{g, select, male {He} female {She} other {They}} replied';

        $this->assertEquals('She replied', $this->interpolator->interpolate($pattern, ['g' => 'female'], 'en-US'));
        $this->assertEquals('They replied', $this->interpolator->interpolate($pattern, ['g' => 'nonbinary'], 'en-US'));
    }

    public function testNestedPlaceholdersResolveInsideIcuBranchesWithoutIntl()
    {
        $this->requireMissingIntl();

        $this->assertEquals(
            'Hello Sarah, you have 2 msgs',
            $this->interpolator->interpolate(
                'Hello {name}, you have {n, plural, one {# msg} other {# msgs}}',
                ['name' => 'Sarah', 'n' => 2],
                'en-US'
            )
        );
    }

    public function testStyleLessIcuFormsResolveWithoutIntl()
    {
        $this->requireMissingIntl();

        $this->assertEquals(
            '1234 units',
            $this->interpolator->interpolate('{v, number} units', ['v' => 1234], 'en-US')
        );
    }

    /**
     * A malformed pattern must not hang or mangle - it is emitted verbatim.
     */
    public function testMalformedIcuIsLeftVerbatimWithoutIntl()
    {
        $this->requireMissingIntl();

        $broken = '{n, plural, one {# item} other {# items}';

        $this->assertEquals($broken, $this->interpolator->interpolate($broken, ['n' => 2], 'en-US'));
    }

    public function testUnknownArgumentInIcuIsLeftVerbatimWithoutIntl()
    {
        $this->requireMissingIntl();

        $pattern = '{missing, plural, one {# item} other {# items}}';

        $this->assertEquals($pattern, $this->interpolator->interpolate($pattern, ['n' => 2], 'en-US'));
    }

    /**
     * A parameter value that itself looks like ICU must not be re-scanned.
     * Substituting the value into the branch before recursing made this recurse
     * until memory was exhausted - an uncatchable fatal in a class that promises
     * never to crash.
     */
    public function testIcuValueThatLooksLikeIcuDoesNotRecurseForever()
    {
        $this->requireMissingIntl();

        $result = $this->interpolator->interpolate(
            '{n, plural, other {#}}',
            ['n' => '{n, plural, other {#}}'],
            'en'
        );

        $this->assertNotEquals('', $result);
    }

    /**
     * A nested plural supplies its own '#'; the outer value must not clobber it.
     */
    public function testNestedPluralKeepsItsOwnHashValue()
    {
        $this->requireMissingIntl();

        $this->assertEquals(
            '7 b / 5 a',
            $this->interpolator->interpolate(
                '{a, plural, other {{b, plural, other {# b}} / # a}}',
                ['a' => 5, 'b' => 7],
                'en'
            )
        );
    }

    public function testDeeplyNestedIcuDoesNotExhaustMemory()
    {
        $this->requireMissingIntl();

        $deep = str_repeat('{n, plural, other {', 200) . '#' . str_repeat('}}', 200);

        $this->assertNotEquals('', $this->interpolator->interpolate($deep, ['n' => 1], 'en'));
    }

    /**
     * 1, 1.0 and "1.0" must all take the `one` branch.
     */
    public function testOneBranchSelectedForFloatAndNumericStringWithoutIntl()
    {
        $this->requireMissingIntl();

        $pattern = '{n, plural, one {# item} other {# items}}';

        foreach ([1, 1.0, '1', '1.0'] as $value) {
            $this->assertStringContainsString(
                'item',
                $this->interpolator->interpolate($pattern, ['n' => $value], 'en'),
                'Value ' . var_export($value, true) . ' must take the one branch'
            );
            $this->assertStringNotContainsString(
                'items',
                $this->interpolator->interpolate($pattern, ['n' => $value], 'en')
            );
        }
    }

    public function testNumberFallsBackToPlainStringWithoutIntl()
    {
        if (extension_loaded('intl')) {
            $this->markTestSkipped('This test covers the no-intl degradation path');
        }

        $this->assertEquals(
            'Count: 1234',
            $this->interpolator->interpolate('Count: {n}', ['n' => 1234])
        );
    }

    // ---------------------------------------------------------------
    // ICU plural rules - expected values generated by the JS SDK
    // ---------------------------------------------------------------

    /**
     * 21 -> "one" and 111 -> "many" are the cases that catch naive
     * implementations of the Russian plural rules.
     */
    public function testRussianPluralCategories()
    {
        $this->requireIntl();

        $pattern = '{n, plural, one {# отзыв} few {# отзыва} many {# отзывов} other {# отзыва}}';

        $expected = [
            1 => '1 отзыв',
            2 => '2 отзыва',
            5 => '5 отзывов',
            21 => '21 отзыв',
            22 => '22 отзыва',
            25 => '25 отзывов',
            100 => '100 отзывов',
            111 => '111 отзывов',
        ];

        foreach ($expected as $n => $want) {
            $this->assertEquals(
                $want,
                $this->interpolator->interpolate($pattern, ['n' => $n], 'ru-RU'),
                "Russian plural for n={$n}"
            );
        }
    }

    /**
     * Arabic has six categories. Note the expected output uses Arabic-Indic
     * digits (٣, ١١, ١٠٠) - ar-EG's numbering system, not ASCII.
     */
    public function testArabicPluralCategories()
    {
        $this->requireIntl();

        $pattern = '{n, plural, zero {لا مراجعات} one {مراجعة} two {مراجعتان} few {# مراجعات} many {# مراجعة} other {# مراجعة}}';

        $expected = [
            0 => 'لا مراجعات',
            1 => 'مراجعة',
            2 => 'مراجعتان',
            3 => '٣ مراجعات',
            11 => '١١ مراجعة',
            100 => '١٠٠ مراجعة',
        ];

        foreach ($expected as $n => $want) {
            $this->assertEquals(
                $want,
                $this->interpolator->interpolate($pattern, ['n' => $n], 'ar-EG'),
                "Arabic plural for n={$n}"
            );
        }
    }

    public function testEnglishPluralCategories()
    {
        $this->requireIntl();

        $pattern = '{n, plural, one {# item} other {# items}}';

        $this->assertEquals('0 items', $this->interpolator->interpolate($pattern, ['n' => 0], 'en-US'));
        $this->assertEquals('1 item', $this->interpolator->interpolate($pattern, ['n' => 1], 'en-US'));
        $this->assertEquals('2 items', $this->interpolator->interpolate($pattern, ['n' => 2], 'en-US'));
    }

    public function testIcuSelect()
    {
        $this->requireIntl();

        $pattern = '{g, select, female {She} male {He} other {They}} replied';

        $this->assertEquals('She replied', $this->interpolator->interpolate($pattern, ['g' => 'female'], 'en-US'));
        $this->assertEquals('They replied', $this->interpolator->interpolate($pattern, ['g' => 'nonbinary'], 'en-US'));
    }

    /**
     * A malformed ICU pattern must NOT throw and must NOT blank the string -
     * it falls back to simple substitution, which leaves the ICU-shaped slot
     * untouched because its key contains commas.
     */
    public function testMalformedIcuFallsBackToTemplateUnchanged()
    {
        $this->requireIntl();

        $broken = '{n, plural, one {# item} other {# items}'; // missing closing brace

        $this->assertEquals(
            $broken,
            $this->interpolator->interpolate($broken, ['n' => 2], 'en-US')
        );
    }

    // ---------------------------------------------------------------
    // Locale-aware number formatting
    // ---------------------------------------------------------------

    public function testNumberFormattingPerLocale()
    {
        $this->requireIntl();

        // ru-RU groups with U+00A0 NO-BREAK SPACE, not an ASCII space.
        $expected = [
            'de-DE' => '1.234,5',
            'ru-RU' => "1\xc2\xa0234,5",
            'en-US' => '1,234.5',
            'ar-EG' => '١٬٢٣٤٫٥',
        ];

        foreach ($expected as $locale => $want) {
            $this->assertEquals(
                $want,
                $this->interpolator->interpolate('{v}', ['v' => 1234.5], $locale),
                "Number formatting for {$locale}"
            );
        }
    }

    /**
     * The ICU number path and the simple path must agree byte-for-byte,
     * otherwise the same value renders differently depending on which
     * syntax an author happened to use.
     */
    public function testIcuNumberMatchesSimplePathExactly()
    {
        $this->requireIntl();

        foreach (['de-DE', 'ru-RU', 'en-US', 'ar-EG'] as $locale) {
            $this->assertEquals(
                $this->interpolator->interpolate('{v}', ['v' => 1234.5], $locale),
                $this->interpolator->interpolate('{v, number}', ['v' => 1234.5], $locale),
                "ICU and simple number paths must agree for {$locale}"
            );
        }
    }

    /**
     * Documented escape hatch: pass a value as a string to opt out of
     * grouping separators - for IDs, codes and version numbers.
     */
    public function testStringValueOptsOutOfNumberFormatting()
    {
        $this->requireIntl();

        $this->assertEquals(
            'Order 1234567',
            $this->interpolator->interpolate('Order {id}', ['id' => '1234567'], 'de-DE')
        );

        $this->assertEquals(
            'Order 1.234.567',
            $this->interpolator->interpolate('Order {id}', ['id' => 1234567], 'de-DE')
        );
    }

    // ---------------------------------------------------------------
    // Dates
    //
    // IntlDateFormatter uses the runtime's default timezone, so a fixture
    // pinned to a bare date is NOT portable across CI boxes (the JS SDK hit
    // exactly this: Date.UTC(2026,6,8) rendered "Jul 7, 2026" at UTC-6).
    // These tests pin the timezone explicitly and assert on FORMAT.
    // ---------------------------------------------------------------

    public function testDateFormattingIsLocaleAware()
    {
        $this->requireIntl();

        $originalTz = date_default_timezone_get();
        date_default_timezone_set('UTC');

        try {
            // Midday UTC: no plausible offset moves this across a date boundary.
            $date = new \DateTimeImmutable('2026-07-08 12:00:00', new \DateTimeZone('UTC'));

            $enUs = $this->interpolator->interpolate('{d}', ['d' => $date], 'en-US');
            $deDe = $this->interpolator->interpolate('{d}', ['d' => $date], 'de-DE');

            // Assert on shape and the correct day, not on an exact fixture string
            // (ICU data formats vary between library versions).
            $this->assertStringContainsString('2026', $enUs);
            $this->assertStringContainsString('8', $enUs);
            $this->assertNotEquals($enUs, $deDe, 'Locales must format dates differently');
            $this->assertStringContainsString('2026', $deDe);
        } finally {
            date_default_timezone_set($originalTz);
        }
    }

    public function testDateFallsBackToIsoWithoutIntl()
    {
        if (extension_loaded('intl')) {
            $this->markTestSkipped('This test covers the no-intl degradation path');
        }

        $date = new \DateTimeImmutable('2026-07-08 12:00:00', new \DateTimeZone('UTC'));

        $this->assertEquals(
            '2026-07-08',
            $this->interpolator->interpolate('{d}', ['d' => $date])
        );
    }
}
